# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d4e0ed19913b985122f9f86816862255"
application_url = "https://ultimate-alter-cord-istanbul.trycloudflare.com"
embedded = true
name = "module-b"
handle = "module-b"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://ultimate-alter-cord-istanbul.trycloudflare.com/auth/callback",
  "https://ultimate-alter-cord-istanbul.trycloudflare.com/auth/shopify/callback",
  "https://ultimate-alter-cord-istanbul.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "quickstart-1add1160.myshopify.com"
automatically_update_urls_on_dev = true
