# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "462cb46cfb28d0dc078a3a6349f8edf5"
name = "module-a"
handle = "module-a"
application_url = "https://participant-spend-martha-join.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-1add1160.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://participant-spend-martha-join.trycloudflare.com/auth/callback",
  "https://participant-spend-martha-join.trycloudflare.com/auth/shopify/callback",
  "https://participant-spend-martha-join.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
