# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d4e0ed19913b985122f9f86816862255"
name = "module-b"
handle = "module-b"
application_url = "https://blond-tom-smart-limited.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-1add1160.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://blond-tom-smart-limited.trycloudflare.com/auth/callback",
  "https://blond-tom-smart-limited.trycloudflare.com/auth/shopify/callback",
  "https://blond-tom-smart-limited.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
